var ZONES = [
  { id: 'all', label: '全部', icon: '🌍' },
  { id: 'wild', label: '野生', icon: '🦁' },
  { id: 'farm', label: '农场', icon: '🚜' },
  { id: 'birds', label: '鸟类', icon: '🦜' },
  { id: 'ocean', label: '海洋', icon: '🐬' },
  { id: 'pet', label: '宠物', icon: '🐾' }
];

var animals = [
  { id: 'lion', zone: 'wild', emoji: '🦁', english: 'Lion', chinese: '狮子' },
  { id: 'tiger', zone: 'wild', emoji: '🐯', english: 'Tiger', chinese: '老虎' },
  { id: 'leopard', zone: 'wild', emoji: '🐆', english: 'Leopard', chinese: '豹子' },
  { id: 'elephant', zone: 'wild', emoji: '🐘', english: 'Elephant', chinese: '大象' },
  { id: 'giraffe', zone: 'wild', emoji: '🦒', english: 'Giraffe', chinese: '长颈鹿' },
  { id: 'zebra', zone: 'wild', emoji: '🦓', english: 'Zebra', chinese: '斑马' },
  { id: 'rhino', zone: 'wild', emoji: '🦏', english: 'Rhino', chinese: '犀牛' },
  { id: 'hippo', zone: 'wild', emoji: '🦛', english: 'Hippo', chinese: '河马' },
  { id: 'panda', zone: 'wild', emoji: '🐼', english: 'Panda', chinese: '熊猫' },
  { id: 'bear', zone: 'wild', emoji: '🐻', english: 'Bear', chinese: '熊' },
  { id: 'monkey', zone: 'wild', emoji: '🐒', english: 'Monkey', chinese: '猴子' },
  { id: 'gorilla', zone: 'wild', emoji: '🦍', english: 'Gorilla', chinese: '大猩猩' },
  { id: 'kangaroo', zone: 'wild', emoji: '🦘', english: 'Kangaroo', chinese: '袋鼠' },
  { id: 'koala', zone: 'wild', emoji: '🐨', english: 'Koala', chinese: '考拉' },
  { id: 'camel', zone: 'wild', emoji: '🐫', english: 'Camel', chinese: '骆驼' },
  { id: 'fox', zone: 'wild', emoji: '🦊', english: 'Fox', chinese: '狐狸' },
  { id: 'wolf', zone: 'wild', emoji: '🐺', english: 'Wolf', chinese: '狼' },
  { id: 'deer', zone: 'wild', emoji: '🦌', english: 'Deer', chinese: '鹿' },
  { id: 'crocodile', zone: 'wild', emoji: '🐊', english: 'Crocodile', chinese: '鳄鱼' },
  { id: 'snake', zone: 'wild', emoji: '🐍', english: 'Snake', chinese: '蛇' },
  { id: 'frog', zone: 'wild', emoji: '🐸', english: 'Frog', chinese: '青蛙' },
  { id: 'turtle', zone: 'wild', emoji: '🐢', english: 'Turtle', chinese: '乌龟' },
  { id: 'squirrel', zone: 'wild', emoji: '🐿️', english: 'Squirrel', chinese: '松鼠' },
  { id: 'raccoon', zone: 'wild', emoji: '🦝', english: 'Raccoon', chinese: '浣熊' },
  { id: 'otter', zone: 'wild', emoji: '🦦', english: 'Otter', chinese: '水獭' },
  { id: 'bat', zone: 'wild', emoji: '🦇', english: 'Bat', chinese: '蝙蝠' },
  { id: 'lizard', zone: 'wild', emoji: '🦎', english: 'Lizard', chinese: '蜥蜴' },
  { id: 'horse', zone: 'farm', emoji: '🐴', english: 'Horse', chinese: '马' },
  { id: 'cow', zone: 'farm', emoji: '🐄', english: 'Cow', chinese: '奶牛' },
  { id: 'sheep', zone: 'farm', emoji: '🐑', english: 'Sheep', chinese: '绵羊' },
  { id: 'pig', zone: 'farm', emoji: '🐷', english: 'Pig', chinese: '猪' },
  { id: 'goat', zone: 'farm', emoji: '🐐', english: 'Goat', chinese: '山羊' },
  { id: 'chicken', zone: 'farm', emoji: '🐔', english: 'Chicken', chinese: '鸡' },
  { id: 'duck', zone: 'farm', emoji: '🦆', english: 'Duck', chinese: '鸭子' },
  { id: 'goose', zone: 'farm', emoji: '🪿', image: 'images/animals/goose.svg', english: 'Goose', chinese: '鹅' },
  { id: 'turkey', zone: 'farm', emoji: '🦃', english: 'Turkey', chinese: '火鸡' },
  { id: 'rabbit', zone: 'farm', emoji: '🐰', english: 'Rabbit', chinese: '兔子' },
  { id: 'buffalo', zone: 'farm', emoji: '🐃', english: 'Buffalo', chinese: '水牛' },
  { id: 'owl', zone: 'birds', emoji: '🦉', english: 'Owl', chinese: '猫头鹰' },
  { id: 'eagle', zone: 'birds', emoji: '🦅', english: 'Eagle', chinese: '老鹰' },
  { id: 'parrot', zone: 'birds', emoji: '🦜', english: 'Parrot', chinese: '鹦鹉' },
  { id: 'peacock', zone: 'birds', emoji: '🦚', english: 'Peacock', chinese: '孔雀' },
  { id: 'flamingo', zone: 'birds', emoji: '🦩', english: 'Flamingo', chinese: '火烈鸟' },
  { id: 'swan', zone: 'birds', emoji: '🦢', english: 'Swan', chinese: '天鹅' },
  { id: 'penguin', zone: 'birds', emoji: '🐧', english: 'Penguin', chinese: '企鹅' },
  { id: 'dolphin', zone: 'ocean', emoji: '🐬', english: 'Dolphin', chinese: '海豚' },
  { id: 'whale', zone: 'ocean', emoji: '🐋', english: 'Whale', chinese: '鲸鱼' },
  { id: 'shark', zone: 'ocean', emoji: '🦈', english: 'Shark', chinese: '鲨鱼' },
  { id: 'octopus', zone: 'ocean', emoji: '🐙', english: 'Octopus', chinese: '章鱼' },
  { id: 'seal', zone: 'ocean', emoji: '🦭', image: 'images/animals/seal.svg', english: 'Seal', chinese: '海豹' },
  { id: 'crab', zone: 'ocean', emoji: '🦀', english: 'Crab', chinese: '螃蟹' },
  { id: 'cat', zone: 'pet', emoji: '🐱', english: 'Cat', chinese: '猫' },
  { id: 'dog', zone: 'pet', emoji: '🐶', english: 'Dog', chinese: '狗' },
  { id: 'hamster', zone: 'pet', emoji: '🐹', english: 'Hamster', chinese: '仓鼠' },
  { id: 'mouse', zone: 'pet', emoji: '🐭', english: 'Mouse', chinese: '老鼠' }
];

SceneApp.init({ items: animals, zones: ZONES, sentences: ANIMAL_SENTENCES });
