var ANIMAL_SENTENCES = {
  lion:      { en: 'This is a lion.', zh: '这是一只狮子。' },
  tiger:     { en: 'The tiger runs fast.', zh: '老虎跑得很快。' },
  leopard:   { en: 'I see a leopard.', zh: '我看见一只豹子。' },
  elephant:  { en: 'The elephant is big.', zh: '大象很大。' },
  giraffe:   { en: 'The giraffe has a long neck.', zh: '长颈鹿脖子很长。' },
  zebra:     { en: 'The zebra has stripes.', zh: '斑马有条纹。' },
  rhino:     { en: 'The rhino is strong.', zh: '犀牛很强壮。' },
  hippo:     { en: 'The hippo lives in water.', zh: '河马住在水里。' },
  panda:     { en: 'I love the panda.', zh: '我喜欢熊猫。' },
  bear:      { en: 'The bear is furry.', zh: '熊毛茸茸的。' },
  monkey:    { en: 'The monkey likes bananas.', zh: '猴子喜欢香蕉。' },
  gorilla:   { en: 'The gorilla is big and strong.', zh: '大猩猩又大又壮。' },
  kangaroo:  { en: 'The kangaroo can jump.', zh: '袋鼠会跳。' },
  koala:     { en: 'The koala lives in a tree.', zh: '考拉住在树上。' },
  camel:     { en: 'The camel lives in the desert.', zh: '骆驼住在沙漠里。' },
  fox:       { en: 'The fox is clever.', zh: '狐狸很聪明。' },
  wolf:      { en: 'The wolf howls at night.', zh: '狼在夜里嚎叫。' },
  deer:      { en: 'The deer runs in the forest.', zh: '鹿在森林里跑。' },
  crocodile: { en: 'The crocodile has sharp teeth.', zh: '鳄鱼有尖牙。' },
  snake:     { en: 'The snake is long.', zh: '蛇很长。' },
  frog:      { en: 'The frog can jump.', zh: '青蛙会跳。' },
  turtle:    { en: 'The turtle moves slowly.', zh: '乌龟走得很慢。' },
  squirrel:  { en: 'The squirrel likes nuts.', zh: '松鼠喜欢坚果。' },
  raccoon:   { en: 'The raccoon is cute.', zh: '浣熊很可爱。' },
  otter:     { en: 'The otter swims in the river.', zh: '水獭在河里游泳。' },
  bat:       { en: 'The bat flies at night.', zh: '蝙蝠在夜里飞。' },
  lizard:    { en: 'The lizard likes the sun.', zh: '蜥蜴喜欢晒太阳。' },
  horse:     { en: 'I ride a horse.', zh: '我骑马。' },
  cow:       { en: 'The cow gives us milk.', zh: '奶牛给我们牛奶。' },
  sheep:     { en: 'The sheep has soft wool.', zh: '绵羊的毛很软。' },
  pig:       { en: 'The pig loves mud.', zh: '猪喜欢玩泥。' },
  goat:      { en: 'The goat eats grass.', zh: '山羊吃草。' },
  chicken:   { en: 'The chicken lays eggs.', zh: '鸡会下蛋。' },
  duck:      { en: 'The duck says quack.', zh: '鸭子嘎嘎叫。' },
  goose:     { en: 'The goose can swim.', zh: '鹅会游泳。' },
  turkey:    { en: 'The turkey is a big bird.', zh: '火鸡是一种大鸟。' },
  rabbit:    { en: 'The rabbit has long ears.', zh: '兔子有长耳朵。' },
  buffalo:   { en: 'The buffalo is very strong.', zh: '水牛非常强壮。' },
  owl:       { en: 'The owl stays awake at night.', zh: '猫头鹰夜里醒着。' },
  eagle:     { en: 'The eagle flies very high.', zh: '老鹰飞得很高。' },
  parrot:    { en: 'The parrot can talk.', zh: '鹦鹉会说话。' },
  peacock:   { en: 'The peacock has pretty feathers.', zh: '孔雀有漂亮的羽毛。' },
  flamingo:  { en: 'The flamingo is pink.', zh: '火烈鸟是粉色的。' },
  swan:      { en: 'The swan is white.', zh: '天鹅是白色的。' },
  penguin:   { en: 'The penguin walks on ice.', zh: '企鹅在冰上走。' },
  dolphin:   { en: 'The dolphin is very smart.', zh: '海豚很聪明。' },
  whale:     { en: 'The whale is very big.', zh: '鲸鱼非常大。' },
  shark:     { en: 'The shark swims in the sea.', zh: '鲨鱼在海里游。' },
  octopus:   { en: 'The octopus has eight arms.', zh: '章鱼有八条触手。' },
  seal:      { en: 'The seal loves the sea.', zh: '海豹喜欢大海。' },
  crab:      { en: 'The crab walks sideways.', zh: '螃蟹横着走。' },
  cat:       { en: 'I have a cat.', zh: '我有一只猫。' },
  dog:       { en: 'The dog is my friend.', zh: '狗是我的朋友。' },
  hamster:   { en: 'The hamster is small and cute.', zh: '仓鼠又小又可爱。' },
  mouse:     { en: 'The mouse is tiny.', zh: '老鼠很小。' }
};
